name: 'Generate native models'
description: 'Generate native models from thrift schema'
inputs:
  personal-access-token:
    description: 'Personal access token used to interact with repo'
    required: true
  version:
    description: 'Version of MAPI models'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.personal-access-token }}
    - ${{ inputs.version }}