name: 'Generate native models'
description: 'Generate native models from thrift schema'
inputs:
  github_token:
    description: 'Github token used to interact with repo'
    required: true
  version:
    description: 'Release version'
    required: true
  tag:
    description: 'Release tag'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.version }}
    - ${{ inputs.tag }}