/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.8.10"

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
    signing

    id("com.microsoft.thrifty") version "3.1.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api("org.apache.commons:commons-math3:3.6.1")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation("com.google.guava:guava:31.1-jre")

    implementation("com.microsoft.thrifty:thrifty-runtime-jvm:3.1.0")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

val javadocJar by tasks.creating(Jar::class) {
    // There are no docs here
    archiveClassifier.set("javadoc")
}

artifacts {
    archives(javadocJar)
}

buildscript {
    dependencies {
        classpath("com.microsoft.thrifty:thrifty-gradle-plugin:3.1.0")
    }
}

apply {
    plugin("com.microsoft.thrifty")
}

thrifty {
    // Optionally configure things, see thrifty-gradle-plugin/README.md
    // for all the details
    sourceDir("../../thrift")
//    outputDir("gen-kotlin")
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "org.gradle.sample"
            artifactId = "library"
            version = "1.4"

            from(components["kotlin"])
        }
    }
}