name: Generate native models
on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Define branch name'
        required: true
        default: 'main'

jobs:
  generate_native_models:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: ./.github/actions/native-models
        name: Generate native models
        with:
          personal-access-token: ${{ secrets.GEN_SWIFT_ACCESS_TOKEN }}
          branch-name: ${{ inputs.branch_name }}
  release_snapshot_sonatype:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch_name }}
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
          cache: sbt
      - name: Release Snapshot to Sonatype
        run: |
          echo "setting git config"
          git config user.email "david.lawes@guardian.co.uk"
          git config user.name "David Lawes"

          echo $PGP_SECRET | base64 --decode | gpg --batch --import
          export GPG_TTY=$(tty)
          echo "Releasing version v0.0.3-006-SNAPSHOT Sonatype as snapshot"

          sbt "clean" "project scalaModels" "set isSnapshot := true" "release release-version v0.0.3-006-SNAPSHOT with-defaults"
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}