name: Generate native models
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Define version'
        required: true
        default: '0.0.1'

jobs:
  generate_native_models:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: ./.github/actions/native-models
        name: Generate native models
        with:
          personal-access-token: ${{ secrets.GEN_SWIFT_ACCESS_TOKEN }}
          version: ${{ inputs.version }}