name: Lint

on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  lint_proto_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint proto files
        run: |
          brew install protolint
          protolint ./proto/.