name: Release Snapshot to Sonatype

on:
  release:
    types: [published]

jobs:
  release_snapshot_sonatype:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 8
          cache: sbt
      - name: Release Snapshot to Sonatype
        run: |
          VERSION = ${{ github.event.release.tag_name }}
          IS_SNAPSHOT = ${{ github.event.release.prerelease }}
          HAS_VERSION_SUFFIX = ${VERSION: -9} == "-SNAPSHOT"
          if [[ ${VERSION:0:1} == "v" ]] ; then
            VERSION=${VERSION:1}
          fi
          if [[ HAS_VERSION_SUFFIX ]] && [[ !IS_SNAPSHOT ]] ; then
              echo "Version must not end in -SNAPSHOT. Exiting."
              exit 1
          elif [[ !HAS_VERSION_SUFFIX ]] && [[ IS_SNAPSHOT ]] ; then
              echo "Version must end in -SNAPSHOT. Adding -SNAPSHOT suffix"
              VERSION="$VERSION-SNAPSHOT"
          fi
          echo $PGP_SECRET | base64 --decode | gpg --batch --import
          export GPG_TTY=$(tty)
          echo "Releasing version $VERSION Sonatype as snapshot"
          sbt "clean" "project scalaModels" "set isSnapshot := $IS_SNAPSHOT" "release release-version $VERSION with-defaults"
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}