name: Release Snapshot to Sonatype

on:
  release:
    types: [published]

jobs:
  release_snapshot_sonatype:
    if: "github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: scala-release-commits-version
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
          cache: sbt
      - name: Release Snapshot to Sonatype
        run: |
          echo "setting git config"
          git config user.email "david.lawes@guardian.co.uk"
          git config user.name "David Lawes"

          git push origin :${{ github.event.release.tag_name }}
          git tag -d ${{ github.event.release.tag_name }}

          echo "RELEASE_VERSION= $GITHUB_REF"
          echo "Tag name = ${{ github.event.release.tag_name }}"

          VERSION=${{ github.event.release.tag_name }}
          if [[ ${VERSION:0:1} == "v" ]] ; then
            VERSION=${VERSION:1}
          fi
          if [[ ${VERSION: -9} != "-SNAPSHOT" ]] ; then
            echo "Version must end in -SNAPSHOT. Adding -SNAPSHOT suffix"
            VERSION="$VERSION-SNAPSHOT"
          fi
          echo $PGP_SECRET | base64 --decode | gpg --batch --import
          export GPG_TTY=$(tty)
          echo "Releasing version $VERSION Sonatype as snapshot"

          sbt "clean" "project scalaModels" "set isSnapshot := true" "release release-version $VERSION with-defaults"
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}